export const ASSET_TYPES = {
  FOLDER: 'FOLDER',
  ALBUM: 'ALBUM',
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  SONG: 'SONG'
}

export const PERSON_POST_STATUSES = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  AWAITS_REVIEW: 'AWAITS_REVIEW',
  IN_REVIEW: 'IN_REVIEW',
  READY_TO_PUBLISH: 'READY_TO_PUBLISH',
  PUBLISHED: 'PUBLISHED'
}