import actionCreator from 'utils/actionCreator';

export const actionTypes = {
  PERSONS_INITIAL_STATE: 'PERSONS_INITIAL_STATE',

  CREATE_PERSON: 'CREATE_PERSON',
  CREATE_PERSON_SUCCESS: 'CREATE_PERSON_SUCCESS',
  CREATE_PERSON_FAIL: 'CREATE_PERSON_FAIL',
  
  GET_PERSONS: 'GET_PERSONS',
  GET_PERSONS_SUCCESS: 'GET_PERSONS_SUCCESS',
  GET_PERSONS_FAIL: 'GET_PERSONS_FAIL',

  DELETE_PERSONS_SUCCESS: 'DELETE_PERSONS_SUCCESS',
  DELETE_PERSONS_FAILED: 'DELETE_PERSONS_FAILED',
}

export const actions = actionCreator(actionTypes);