import actionCreator from 'utils/actionCreator';

export const actionTypes = {
  SET_USER: 'SET_USER',
  
  UPDATE_PAGINATION: 'UPDATE_PAGINATION',
  UPDATE_SEARCH_TERM: 'UPDATE_SEARCH_TERM',
  UPDATE_SORT: 'UPDATE_SORT',

  TOGGLE_IS_LOADING: 'TOGGLE_IS_LOADING',

  CREATE_ASSET: 'CREATE_ASSET',
  CREATE_ASSET_SUCCESS: 'CREATE_ASSET_SUCCESS',
  CREATE_ASSET_FAIL: 'CREATE_ASSET_FAIL',

  GET_ASSETS: 'GET_ASSETS',
  GET_ASSETS_SUCCESS: 'GET_ASSETS_SUCCESS',
  GET_ASSETS_FAIL: 'GET_ASSETS_FAIL',
}

export const actions = actionCreator(actionTypes);